config/routes.rb
Rails.application.routes.draw do
  resources :listings
  devise_for :users
  get "/", to: "pages#home", as: "root"
  get "/payments/success", to: "payments#success" #add route for payment success page"
  post "/payments/webhook", to: "payments#webhook" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
    enum condition: {New: 1, Used: 0}
    belongs_to :location 
    belongs_to :user
    belongs_to :size
    has_many_attached :picture
    
    validates :brand, :price,:condition, :location_id, :size_id, :picture, presence: true
  #this method to call the first image in the image array to show since  a listing can have many pictures. Used in _listing.html.erb line 27
    def listing_attachment 
        picture[0]
    end

end

app/models/location.rb
class Location < ApplicationRecord
    has_many :listings, dependent: :destroy
end

app/models/size.rb
class Size < ApplicationRecord
    has_many :listings, dependent: :destroy  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_vars, only: [:new, :create, :edit, :update]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]


  # GET /listings
  # GET /listings.json
  def index

    @q = Listing.ransack(params[:q])
    @listings = @q.result(distinct: true)
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: @listing.brand,
            description: @listing.model,
            amount: @listing.price * 100,
            currency: 'aud',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                user_id: current_user.id,
                listing_id: @listing.id
            }
        },
        success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@listing.id}",
        cancel_url: "#{root_url}listings"
    )

    @session_id = session.id
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.create(listing_params)
    
    if @listing.errors.any?
      render "new"
      else
      redirect_to listings_path
      end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:brand, :model, :colorway, :price, :condition, :description, :location_id, :size_id,:user_id,picture: [])
    end

    def set_vars
      @conditions = Listing.conditions.keys
      @locations = Location.all
      @sizes = Size.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home    

    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    def success

    end

    def webhook
        payment_id= params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_id)
    listing_id = payment.metadata.listing_id
    user_id = payment.metadata.user_id

    p "listing id " + listing_id
    p "user id " + user_id

    status 200
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoesMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
  
  <%= render  "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form|%>
<div class="container ">
<h1 class="font-weight-bold font-italic">New Listing</h1>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, :min => 0  %>
  </div>
  <div class="field">
     <%= form.label :size_id %>  
    <%= form.select(:size_id, @sizes.map{|l| [l.size, l.id]}) %> 
  </div>
<% @conditions.each do |option| %>
    <div class="field">
    <%= form.radio_button :condition, option %>
    <%= form.label "condition_#{option}".to_sym, option, value: listing.condition%>
    <div>
    <% end %>
  
  <div class="field">
     <%= form.label :location_id %>  
    <%= form.select(:location_id, @locations.map{|l| [l.state, l.id]}) %> 
  </div>

   <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>  

  <div class="field">
     <%= form.label :picture %>  
    <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg', multiple: true %> 
  </div>

  <div class="actions">
    <%= form.submit "List your shoes", class:"btn btn-success" %>
  </div>
</div>  
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>


<%= render  "shared/listing" %>

app/views/listings/new.html.erb
<%= render 'form', listing: @listing %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container d-flex flex-column flex-md-row px-2 my-2 my-my-5">
  
    <div class="col-sm-8 col-md-6">
      <div id="carouselExampleControls" class="carousel slide carousel-fade " data-ride="carousel">

        <div class="carousel-inner centered-carousel-item ">
          <%@listing.picture.each_with_index do |p,i|%>
            <div class="carousel-item align-content-center <%= "active " if i==0 %>">
              <%= image_tag  p, style:"width:200%" %>
            </div>
          <%end%>
        </div>

        <a class="carousel-control-prev " href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon " aria-hidden="true"></span>
          <span class="sr-only"></span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
 

  <div class="sidebar col-lg-4 mx-auto">
  
    <div class="col-12 p-3 container">
       <%if current_user.id != @listing.user_id%>
      <button data-stripe="payment", class="buy-btn btn-outline-success"><h4>Check out </h4></button>
      <script src="https://js.stripe.com/v3/"></script>

      <script>
        document
          .querySelector("[data-stripe='payment']")
          .addEventListener("click", () => {
            const stripe = Stripe(
              "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
            );

            stripe.redirectToCheckout({
              sessionId: "<%= @session_id %>"
            });
          });
      </script> 
      <%end%>

      <div>
      <h2><%= number_to_currency(@listing.price) %></h2>
      </div> <br>
      <h4>Details</h4>
      <div>
      <%= @listing.brand%> <%= @listing.model%>
      </div>
      
      <div>
      Size <%= @listing.size.size%> US - <%= @listing.condition ? "New" : "Used"%>
      </div>
      <div>
      
      </div>
      <div>
      Location : <%= @listing.location.state%>
      </div>
      <p> <%= @listing.description%></p>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="container">
    <div class="push-spaces">
        <div class="jumbotron bg-transparent">
            <h1 class="display-4 text-center">BUY AND SELL YOUR SNEAKER</h1>
            <p class="lead btn-lg mx-auto welcome-text text-center">On Shoes Market, buy and sell sneakers & shoes from Air Jordan, Adidas, Nike, Yeezy, Converse, New Balance and more!</p>
            <p class="lead text-center">
                <%= link_to  "Find out more", listings_path, class: "btn btn-dark btn-lg" %>
            </p>
        </div>
    </div>
</div>

app/views/payments/success.html.erb
You've successfully made a payment!
Thanks your using our service.
<%= link_to "Go back", listings_path%>

app/views/shared/_error.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_listing.html.erb
<%# search function using ransack gem%>

    
<%= search_form_for @q do |f| %>
    <div class="text-center">
        <div class="btn-group" role="group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fa fa-search"></i></span>
                </div>
                <%= f.search_field :brand_or_model_cont, class:"form-control" ,placeholder:"Find shoes by brand or model...", style:"width:30rem"%>

            </div>
            <%= f.submit "Search",  class: "btn btn-outline-dark", style:"margin:auto"%>
        </div>
    </div>
<%end%>



<%# listings view%>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 m-5">
<% @listings.each do |listing|%>
    <div class="col">
        <div class="card">
            <%= image_tag  listing.listing_attachment ,style:"width: 100%"%>
            <div class="card-body">
                <h4 class="card-title">
                    <%= listing.brand%>
                </h4>
                <h5 class="card-title mb-2">
                    <%= listing.model%>
                </h5>
                <h5 class="card-subtitle">
                    $<%= listing.price%>
                </h5>
                <%= link_to  "Show", listing , class:"btn btn-outline-primary" %>
    
            </div>
        </div>
    </div>
<%end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
    <div class="container">
        <div class="nav-brand">
            <%= link_to image_tag("logo1.png"),  root_path, class:"logo" %>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class ="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to "Sell",  new_listing_path, class:"padding"%>
                </li>
                <li class="nav-item">
                    <%= link_to "Browse", listings_path, class:"padding" %>
                </li>
                 <%if user_signed_in? %>
                    <li class="nav-item ">
                        <%= link_to  "Profile",  edit_user_registration_path, class: "padding" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  "Sign Out", destroy_user_session_path, method: :delete , class: "padding" %>
                    </li>
                <%else%>
                    <li class="nav-item"><%= link_to  "Log In", new_user_session_path , class: "padding" %></li>
                    <li class="nav-item"><%= link_to  "Sign Up", new_user_registration_path , class: "padding"%></li>
                <%end%>
                
            </ul>
        </div>
    </div>
</nav>